### ISSUE TITLE
Dogs parks in the city

### ISSUE THREAD

**Issue by LanaD-cell** [LanaD-cell/planning-project-demo#1]
**User story**

As a local dog owner, I want to see all the available dog-parks in the city and what they offer.

**Acceptance Criteria**

- [x] The Homepage displays a list of dog-parks in the city.
- [x] Each listing includes the Park name, location and brief description.
- [x] The list is responsive and looks good on all main device sizes.

**Tasks**

- [x] 1. Add an HTML section on the homepage dedicated to dog-parks.
- [x] 2. Style the event list using Bootstrap.
- [x] 3. Add some sample dog-parks including name, location and brief description.
