### ISSUE TITLE
Project Planning - Membership etc.

### ISSUE THREAD

**Issue by LanaD-cell** [LanaD-cell/planning-project-demo#10]
**User Story:** 

As a local dog-owner and first time visitor, I want to join as a member. 

**Acceptance Criteria**

- [ ] A membership form that is simple and easy to use.
- [x] The necessary information should be added to the form: Name (Owner), Name (Dog), Breed, Email, Phone 
       Number  and Message.
- [x] All fields on the form must be completed, except Address field, before the user can submit the form.
- [ ] When the form is completed correctly, the user is taken to a success page.

**Tasks**

- [ ] Implement HTML validation on the form to fit the requirements above.
- [ ] Create a success page to direct users to after submitting the form.
