### ISSUE TITLE
Project Planning - additional services on Membership etc page

### ISSUE THREAD

**Issue by LanaD-cell** [LanaD-cell/planning-project-demo#11]
**User story:**

As a new member to the site, I wish to make social connections through the site to find like minded people. I am also interested information on taking care of my pooch, restaurants that allow dogs and helpful support in case of a doggie emergency.

**Acceptance criteria**

- [ ] Success page contains a Gift (Sponsor Product) for new members.
- [ ] The different information sections is easy to navigate and self explanatory.
- [ ] All form element function and leads to a "Package is on its way" message.
- [ ] The Blog is easy to enter and navigate.
- [ ] The elements fit to all main device sizes.

**Tasks**

 - [ ] Add another Form for a special gift. 
- [ ]- [ ] Add all relevant information: Member Name, membership number, Address (required if voucher is valid).
- [ ] Information section for "Pocket Vet" and a clickable button that connects to registered Veterinarians.
- [ ] Website Blog with individual sections: Taking care of my pooch, eat out with my pooch, Dog sitters and - 
       walkers.
- [ ] Blog section with a message section for membership communication.
