### ISSUE TITLE
Call to action / contact page

### ISSUE THREAD

**Issue by LanaD-cell** [LanaD-cell/planning-project-demo#2]
**User story**

I as a local dog-owner, want to sign up for weekly event updates.

**Acceptance criteria**

- [ ] The page features a form for personal contact information.
- [ ] All contact information of the website is displayed on the page.

**Tasks**

- [ ] Add a HTML form to gather the required information including name, email and/or contact number.

**Comment by LanaD-cell** [comment]
Test
