### ISSUE TITLE
Welcome page

### ISSUE THREAD

**Issue by LanaD-cell** [LanaD-cell/planning-project-demo#3]
**User story**

As a local dog-owner, I am looking for a all website that offers information on the dog-parks in the city.

**Acceptance criteria**

- [ ] 
- [ ] The Homepage features a colorful and inviting Welcome page and is easy to navigate.
- [ ] Some About information is offered.
- [ ] The site is responsive and looks good on all main device sizes.

**Tasks**

- [ ] 
- [ ] Add an HTML section with basic boilerplate setup.
- [ ] Use the CICD for the website and use relevant image elements.
- [ ] Create a responsive navbar, header and footer. All should look good on all main device sizes.

**Comment by LanaD-cell** [comment]
test
