### ISSUE TITLE
Expanded - Welcome page

### ISSUE THREAD

**Issue by LanaD-cell** [LanaD-cell/planning-project-demo#5]
**User story**

As a local dog-owner, I am looking for a all website that offers information on the dog-parks in the city. I would like to see how successful the site is in the form of Membership Picture wall.

**Acceptance criteria**

- [ ] The Picture wall is featured at the bottom of the page.
- [ ] Pictures randomly flip from one to the next.
- [ ] It is responsive and fit to all main device sizes.

**Tasks**

- [ ] Add a HTML section for a Image element.
- [ ] Place the section at the bottom of the page above the floating footer.
- [ ] Create a corresponding text block that shows some details of each image.

**Comment by LanaD-cell** [comment]
test
