### ISSUE TITLE
Expanded - Dog parks in the city

### ISSUE THREAD

**Issue by LanaD-cell** [LanaD-cell/planning-project-demo#6]
**User story**

As a local dog owner, I want to see all the available dog-parks in the city and what they offer. I would like to see a video of each park to see what it looks like live.

**Acceptance criteria**

- [ ] A link to each park section that takes you to a live feed of what the park looks like.
- [ ] The video opens on a pop up window and does not redirect the user.
- [ ] Its fits to all main device sizes and looks good.

**Task**

- [ ] Add a HTML section with a button that links to the pop up window.
- [ ] The video has a closing button.

**Comment by LanaD-cell** [comment]
test
