### ISSUE TITLE
Expanded - Call to action / contact page

### ISSUE THREAD

**Issue by LanaD-cell** [LanaD-cell/planning-project-demo#7]
User story

I as a local dog-owner, want to sign up for weekly event updates. I am also hoping to use the app to meet new people and get some support from professionals.

**Acceptance criteria**

- [ ] A section is added, "Pocket-Vet", that allows the user to contact the registered Veterinarians.
- [ ] The social board allows chats between registered members.

**Tasks**

- [ ] Create a HTML section for both communication boards.
- [ ] Ensure that it is secure and no personal information is being tracked.

**Comment by LanaD-cell** [comment]
test
