### ISSUE TITLE
Project Planning - Homepage

### ISSUE THREAD

**Issue by LanaD-cell** [LanaD-cell/planning-project-demo#8]
**User story:**

As a First-Time Visitor, I need easy a user-friendly design with straight forward navigation, featuring a colourful layout that fits on all my device. Information should be easily accessible.

**Acceptance Criteria**

- [x] The Homepage must fit to all main device sizes and be responsive.
- [x] The navigation must be easy to use.

**Tasks**

- [x] Set up a navbar with Bootstrap, that will be easy to use.
- [x] Arrange elements to optimize UX.

Features to incorporate:
- [x] HTML basic boilerplate
- [x] Navbar
- [x] Header / Footer (floating)
- [x] Hero Img
- [x] About section

**Comment by LanaD-cell** [comment]
All the requirements were met.
