### ISSUE TITLE
Project Planning - Parks

### ISSUE THREAD

**Issue by LanaD-cell** [LanaD-cell/planning-project-demo#9]
**User story:** 

As a local dog-owner, I want to see colourful engaging park profiles that are informative and fun.

**Acceptance Criteria**

- [x] Individual sections for each park.
- [ ] Engaging descriptions of each park. Relevant information i.e.. its name, location, events and extra features 
      should be easily accessible. 
- [x] The page design should be cohesive with the Homepage.

**Tasks**

- [x] Integrate provided image elements for each park.
- [ ] Add a map for each section.
- [x] Add a Information section on each section.
- [ ] Create a button to take the user to the relevant website for each park.
